"""make agent_tool_calls.interaction_id nullable

Revision ID: 7c93dd2ad7ae
Revises: 234f0eeae68d
Create Date: 2026-07-16 14:49:55.984113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c93dd2ad7ae'
down_revision: Union[str, Sequence[str], None] = '234f0eeae68d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_tool_calls', 'interaction_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_tool_calls', 'interaction_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
